dependencies:
  build:
    - python:3.8

build_targets:
   - name: default
     commands:
       - pip install -U wheel
       - pip install -U setuptools
       - python3 -m pip install -U pip
       - pip install tox
       - tox -e py38
       - tox -e style
  
