dependencies:
  build:
    # python:3.7
    - python:2.7

build_targets:
  - name: default
    commands:
      - pip install -r requirements.txt
      # TODO, add template interpolation support for build pack bin paths
      # Adds a symlink to <path to>/bin/python as <path to>/bin/python2
      - bash -c "ln -s $(which python) $(which python)2"
      - make tests
