dependencies:
  build:
    - gradle:6.5.1
    - flutter:1.17.5

build_targets:
  - name: default
    commands:
      - bash -x get_packages.sh

  - name: beta
    dependencies:
      build:
        - flutter:1.17.2
    commands:
      - bash -x get_packages.sh
