dependencies:
  build:
    - go:1.13.4
    - python:3.6

build_targets:
  - name: default
    host_only: true
    commands:
      - go test ./...
      - go build

  - name: release
    build_after:
      - default
    environment:
      - CHANNEL=unstable
    commands:
      - pip install awscli
      - bash release.sh 

  - name: preview_release
    build_after:
      - default
    environment:
      - CHANNEL=preview
    commands:
      - pip install awscli
      - bash release.sh 

  - name: experimental_release
    build_after:
      - default
    environment:
      - CHANNEL=experimental
    commands:
      - pip install awscli
      - bash release.sh 

  - name: linux
    build_after:
      - default
    tags:
      os: linux
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o yb-linux-amd64

  - name: darwin
    build_after:
      - default
    tags:
      os: darwin
    environment:
      - GOOS=darwin
      - GOARCH=amd64
    commands:
      - go build -o yb-darwin-amd64

ci:
  builds:
    - name: test_build
      build_target: default

    - name: exp_release
      build_target: experimental_release
      when: branch CONTAINS '-experimental' AND tagged IS true

    - name: pre_release
      build_target: preview_release
      when: branch CONTAINS '-preview' AND tagged IS true

    - name: release
      build_target: release
      when: branch CONTAINS '-stable' AND tagged IS true

