dependencies:
  build:
    - go:1.12.9
    - python:3.6

build_targets:
  - name: default
    host_only: true
    commands:
      - go test ./...
      - go build

  - name: development
    host_only: true
    commands:
      - go test ./...
      - go build -ldflags "-X 'main.channel=development'"

    # Tagged releases will go to unstable
  - name: release
    build_after:
      - default
    environment:
      - CHANNEL=unstable
    commands:
      - pip install awscli
      - bash release.sh 

  - name: preview_release
    build_after:
      - default
    environment:
      - CHANNEL=preview
    commands:
      - pip install awscli
      - bash release.sh 

  - name: linux
    build_after:
      - default
    tags:
      os: linux
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o yb-linux-amd64

  - name: darwin
    build_after:
      - default
    tags:
      os: darwin
    environment:
      - GOOS=darwin
      - GOARCH=amd64
    commands:
      - go build -o yb-darwin-amd64

ci:
  builds:
    - name: test_build
      build_target: default

    - name: release
      build_target: release
      when: branch IS 'master' AND tagged IS true

    - name: pre_release
      build_target: preview_release
      when: (branch IS NOT 'master') AND tagged IS true

