dependencies:
  build:
    - go:1.14.6

build_targets:
  - name: default
    commands:
      - go test ./...
      - bash -c "go build -ldflags \"-X 'main.date=$(date)'\""

  - name: integration
    build_after:
      - default
    commands:
      - apt-get install -y git
      - bash -c "cd integration-tests; ../yb build -no-container"
      - bash -c "cd integration-tests; ../yb build -no-container python"
      - bash -c "cd integration-tests; ../yb build -no-container gopher"
      - bash -c "cd integration-tests; ../yb build -no-container ruby"
      - bash -c "cd integration-tests; ../yb build -no-container java"

  - name: release
    dependencies:
      build:
        - python:3.7
    build_after:
      - default
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends zip
      - pip install awscli
      - bash package.sh
      - bash release.sh 

  - name: local_test_release
    dependencies:
      build:
        - python:3.7
    host_only: true
    dependencies:
      build:
        - python:3.7
    build_after:
      - default
    environment:
      - TEST_RELEASE=test_me
      - AWS_ACCESS_KEY_ID=only_smeagle_knows
      - AWS_SECRET_ACCESS_KEY=only_smeagle_knows
      - RELEASE_KEY=not known
      - RELEASE_TOKEN=also unknown
      - YB_GIT_BRANCH=refs/tags/v0.0.0-rc0
    commands:
      - pip install awscli
      - bash package.sh
      - bash release.sh
      - rm -f yb
      - unzip yb_v0.0.0-rc0_linux_amd64.zip
      - mv yb_v0.0.0-rc0_linux_amd64/yb yb
      - rmdir yb_v0.0.0-rc0_linux_amd64/
      - ls -lh yb
      - ./yb version
      - rm -f yb
      - tar xf yb-linux-amd64-v0.0.0-rc0.tgz
      - mv yb-linux-amd64 yb
      - ls -lh yb
      - ./yb version

  - name: linux
    build_after:
      - default
    tags:
      os: linux
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o yb-linux-amd64

  - name: darwin
    build_after:
      - default
    tags:
      os: darwin
    environment:
      - GOOS=darwin
      - GOARCH=amd64
    commands:
      - go build -o yb-darwin-amd64

ci:
  builds:
    - name: test_build
      build_target: default

    - name: test_integration
      build_target: integration
      when: branch IS 'master' OR action IS 'pull-request'

    - name: release
      build_target: release
      when: tagged IS true

