dependencies:
  build:
    - go:1.16.3

build_targets:
  - name: default
    commands:
      - release/build.sh yb

  - name: test
    commands:
      - go test -mod=readonly -race -short ./...

  - name: all_tests
    commands:
      - go test -mod=readonly -race ./...

ci:
  builds:
    - name: test_build
      build_target: default
      when: branch IS 'main' OR action IS 'pull_request'

    - name: test
      build_target: test
      when: branch IS 'main' OR action IS 'pull_request'

