dependencies:
  build:
    - go:1.15

build_targets:
  - name: default
    commands:
      - go test ./...
      - release/build.sh yb

  - name: integration
    build_after:
      - default
    commands:
      - apt-get install -y --no-install-recommends git
      - bash -c "cd integration-tests; ../yb build --no-container"
      - bash -c "cd integration-tests; ../yb build --no-container flutter"
      - bash -c "cd integration-tests; ../yb build --no-container python"
      - bash -c "cd integration-tests; ../yb build --no-container gopher"
      - bash -c "cd integration-tests; ../yb build --no-container ruby"
      - bash -c "cd integration-tests; ../yb build --no-container java"

ci:
  builds:
    - name: test_build
      build_target: default
      when: branch IS 'main' OR action IS 'pull_request'

    - name: test_integration
      build_target: integration
      when: branch IS 'main' OR action IS 'pull_request'

