dependencies:
  build:
    - go:1.12.9

build_targets:
  - name: default
    host_only: true
    commands:
      - go test ./...
      - go build

    # Tagged releases will go to unstable
  - name: release
    build_after:
      - default
    environment:
      - CHANNEL=unstable
    commands:
      - bash release.sh 

  - name: development_release
    build_after:
      - default
    environment:
      - CHANNEL=development
    commands:
      - bash release.sh 

  - name: linux
    build_after: 
      - default
    tags:
      os: linux
    environment: 
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o yb-linux-amd64

  - name: darwin
    tags:
      os: darwin
    environment:
      - GOOS=darwin
      - GOARCH=amd64
    commands:
      - go build -o yb-darwin-amd64

ci:
  builds:
    - name: test_build
      build_target: default

    - name: development_release
      build_target: development_release
      when: branch IS NOT 'master'

    - name: release
      build_target: release
      when: branch IS 'master' and tagged IS true

