dependencies:
  build:
    - java:8.252+09
    - maven:3.6.2

build_targets:
  - name: default
    commands:
      - mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install -U -f pom.xml
