dependencies:
  build:
    # TODO Add "matrix like" support
    - ruby:2.7.1

build_targets:
  - name: default
    commands:
      - bundle update --bundler
      - bundle install --jobs=3
      - ./bin/test Gemfile
      - ./bin/test gemfiles/Gemfile.rails-6.0-stable
