dependencies:
  build:
    # TODO MATRIX support ;)
    # ruby:2.4.10
    # ruby:2.3.8
    # ruby:2.5.8
    # ruby:2.6.6
    - ruby:2.7.1

build_targets:
  - name: default
    commands:
      - bundle install --jobs=3
      - bundle exec rake spec rubocop
