# NOTE first iteration, just testing `yb build`
# After fixing how the CLI manages workspaces (currently done using config.yml), we could simplify this a bit
#
build_targets:
  - name: default
    commands:
      - git submodule update --checkout --depth 2

  - name: python
    commands:
      - cp python/.yourbase.flask.yml python/flask/.yourbase.yml
      - cp python/.yourbase.httpie.yml python/httpie/.yourbase.yml
      - bash -c "cd python/flask && yb build -no-container default; git restore ."
      - bash -c "cd python/httpie && yb build -no-container default; git restore ."
      - rm python/flask/.yourbase.yml
      - rm python/httpie/.yourbase.yml

  - name: java
    commands:
      - cp java/.yourbase.RxJava.yml java/RxJava/.yourbase.yml
      - cp java/.yourbase.guava.yml java/guava/.yourbase.yml
      - cp java/.yourbase.java-design-patterns.yml java/java-design-patterns/.yourbase.yml
      - bash -c "cd java/RxJava && yb build -no-container default; git restore ."
      - bash -c "cd java/guava && yb build -no-container default; git restore ."
      - bash -c "cd java/java-design-patterns && yb build -no-container default; git restore ."
      - rm java/RxJava/.yourbase.yml
      - rm java/guava/.yourbase.yml
      - rm java/java-design-patterns/.yourbase.yml

  - name: gopher
    commands:
      - cp go/.yourbase.gg.yml go/gg/.yourbase.yml
      - cp go/.yourbase.gin.yml go/gin/.yourbase.yml
      - bash -c "cd go/gg && yb build -no-container default; git restore ."
      - bash -c "cd go/gin && yb build -no-container default; git restore ."
      - rm go/gg/.yourbase.yml
      - rm go/gin/.yourbase.yml

  - name: ruby
    commands:
      - cp ruby/.yourbase.capistrano.yml ruby/capistrano/.yourbase.yml
      - cp ruby/.yourbase.devise.yml ruby/devise/.yourbase.yml
      - bash -c "cd ruby/capistrano && yb build -no-container default; git restore ."
      - bash -c "cd ruby/devise && yb build -no-container default; git restore ."
      - rm ruby/capistrano/.yourbase.yml
      - rm ruby/devise/.yourbase.yml

  - name: flutter
    commands:
      - cp flutter/.yourbase.flutter-examples.yml flutter/flutter-examples/.yourbase.yml
      - cp flutter/.yourbase.pin_code_test_field.yml flutter/pin_code_test_field/.yourbase.yml
      - bash -c "cd flutter/flutter-examples && yb build -no-container default; git restore ."
      - bash -c "cd flutter/pin_code_test_field && yb build -no-container default; git restore ."
      - bash -c "cd flutter/flutter-examples && yb build -no-container beta; git restore ."
      - bash -c "cd flutter/pin_code_test_field && yb build -no-container beta; git restore ."
      - rm flutter/flutter-examples/.yourbase.yml
      - rm flutter/pin_code_test_field/.yourbase.yml
